# Generated by Django 2.2.7 on 2020-04-28 23:45

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('M', 'Dairy Substitute'), ('B', 'Meat Substitute'), ('C', 'Candy'), ('S', 'Snacks'), ('I', 'Ice Cream'), ('O', 'Other')], default='M', max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='C:\\Users\\frant\\PycharmProjects\\veganBlog\\media')),
                ('ingredients', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
