# Generated by Django 2.2.7 on 2020-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image3',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\frant\\PycharmProjects\\veganBlog\\media'),
        ),
    ]
