# Generated by Django 2.2.7 on 2020-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_name', models.CharField(max_length=512)),
                ('thumbnail_image', models.ImageField(upload_to='C:\\Users\\frant\\PycharmProjects\\veganBlog\\media')),
            ],
        ),
    ]
