# Generated by Django 2.2.7 on 2020-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_auto_20200430_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
